# Manually rebuild stored data from scratch.
name: "Refresh cache"
on:
  workflow_dispatch: {}
jobs:
  "deploy":
    name: "Build and deploy"
    runs-on: "ubuntu-latest"
    steps:
    - name: "Checkout roar"
      uses: "actions/checkout@v4"
      with:
        repository: "RobloxAPI/roar"
        path: "roar"

    - name: "Checkout build-archive"
      uses: "actions/checkout@v4"
      with:
        repository: "RobloxAPI/build-archive"
        path: "build-archive"

    - name: "Checkout ref"
      uses: "actions/checkout@v4"
      with:
        ref: "gh-pages"
        path: "ref"

    - name: "Setup Go"
      uses: "actions/setup-go@v4"
      with:
        go-version-file: "roar/go.mod"
        cache-dependency-path: |
          roar/go.sum

    - name: "Build roar"
      run: |
        go build -C "roar" -v -o "../bin/roar" "./cmd/roar"

    - name: "Generate data"
      run: |
        bin/roar generate \
        --site "roar/site" \
        --source "build-archive/data/" \
        --update \
        --no-cache \
        --disable-pages \
        --disable-icons

    - name: "Store site data"
      run: |
        rm --recursive --force "ref/.roar"
        mkdir --parents "ref/.roar"
        cp --archive "roar/site/data/." "ref/.roar"

    - name: "Commit and push website"
      if: |
        steps.check-cache-build-archive.outputs.cache-hit != 'true' ||
        steps.check-cache-roar.outputs.cache-hit != 'true'
      run: |
        cd "ref"
        git config user.email 'github-actions@github.com'
        git config user.name 'github-actions'
        git add -A
        git commit -m 'Refresh data.'
        git push
      continue-on-error: true
